name: Misc

on:
  pull_request:
  push:
    tags:
      - 'v*'
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: misc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    name: Integration tests
    # If starting the example fails at runtime the integration test will
    # be stuck. Try to limit the damage. The value "10" selected arbitrarily.
    timeout-minutes: 10
    strategy:
      matrix:
        include:
        - os: windows-latest
          script: ".\\tests\\sign-and-verify-win.bat"
        - os: ubuntu-latest
          script: ./tests/sign-and-verify.sh
        - os: macos-latest
          script: ./tests/sign-and-verify.sh
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - run: just install-packages
      # If the example doesn't compile the integration test will
      # be stuck. Check for compilation issues earlier to abort the job
      - name: Check if the key-storage example compiles
        run: cargo check --example key-storage
      - name: Check if the ssh-agent-client example compiles
        run: cargo check --example ssh-agent-client
      - name: Check if the ssh-agent-client-blocking example compiles
        run: cargo check --example ssh-agent-client-blocking
      - name: Run integration tests
        run: ${{ matrix.script }}
