name: Misc

on:
  pull_request:
  push:
    tags:
      - 'v*'
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: misc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    name: Integration tests
    # If starting the example fails at runtime the integration test will
    # be stuck. Try to limit the damage. The value "10" selected arbitrarily.
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        include:
        - os: windows-latest
          windows: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - run: just install-packages
      # If the example doesn't compile the integration test will
      # be stuck. Check for compilation issues earlier to abort the job
      - name: Check if the example compiles
        run: cargo check --example key-storage
      - name: Run integration tests
        run: ./tests/sign-and-verify.sh
        if: ${{ ! matrix.windows }}
      - name: Run integration tests
        run: ".\\tests\\sign-and-verify-win.bat"
        if: ${{ matrix.windows }}
